//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATN_StudentMangement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietLopHP
    {
        public string MaLHP { get; set; }
        public string MaSV { get; set; }
        public Nullable<double> DiemTX1 { get; set; }
        public Nullable<double> DiemTX2 { get; set; }
        public Nullable<double> DiemThi { get; set; }
        public Nullable<double> DiemTongKet { get; set; }
    
        public virtual LopHP LopHP { get; set; }
        public virtual Sinhvien Sinhvien { get; set; }
    }
}
