//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATN_StudentMangement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LopHP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LopHP()
        {
            this.ChiTietLopHPs = new HashSet<ChiTietLopHP>();
        }
    
        public string MaLHP { get; set; }
        public string MaMH { get; set; }
        public string MaGV { get; set; }
        public string Thu { get; set; }
        public Nullable<int> SiSoToiDa { get; set; }
        public string NamHoc { get; set; }
        public string HocKi { get; set; }
        public string TrangThai { get; set; }
        public string Buoi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietLopHP> ChiTietLopHPs { get; set; }
        public virtual GiangVien GiangVien { get; set; }
        public virtual Monhoc Monhoc { get; set; }
    }
}
