//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATN_StudentMangement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monhoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Monhoc()
        {
            this.LopHPs = new HashSet<LopHP>();
        }
    
        public string MaMH { get; set; }
        public string TenMH { get; set; }
        public int SoTinChi { get; set; }
        public Nullable<int> TyLeTX1 { get; set; }
        public Nullable<int> TyLeTX2 { get; set; }
        public Nullable<int> TyLeThi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LopHP> LopHPs { get; set; }
    }
}
